#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.1.1 (64-bit)
#
# Filename    : UFBmod_TRX.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Mar 11 00:12:52 +0100 2021
# SW Build 2960000 on Wed Aug  5 22:57:20 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: UFBmod_TRX.sh [-help]
# usage: UFBmod_TRX.sh [-lib_map_path]
# usage: UFBmod_TRX.sh [-noclean_files]
# usage: UFBmod_TRX.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'UFBmod_TRX.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xpm lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 xil_defaultlib xbip_utils_v3_0_10 c_reg_fd_v12_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_6 xbip_dsp48_addsub_v3_0_6 xbip_addsub_v3_0_6 c_addsub_v12_0_14 c_gate_bit_v12_0_6 xbip_counter_v3_0_6 c_counter_binary_v12_0_14 xlconcat_v2_1_3 xlslice_v1_0_2 fifo_generator_v13_2_5 xlconstant_v1_1_7 util_vector_logic_v2_0_1 c_mux_bit_v12_0_6 c_shift_ram_v12_0_14 xbip_bram18k_v3_0_6 mult_gen_v12_0_16 axi_utils_v2_0_6 cordic_v6_0_16 cmpy_v6_0_18 floating_point_v7_0_17 xfft_v9_1_4 blk_mem_gen_v8_4_4 util_reduced_logic_v2_0_4 xbip_dsp48_multadd_v3_0_6 xbip_multadd_v3_0_15 dds_compiler_v6_0_20)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "UFBmod_TRX.sh - Script generated by export_simulation (Vivado v2020.1.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_proc_sys_reset_0_1/sim/UFBmod_TRX_TRX_proc_sys_reset_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/d117/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/edec/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/cfdd/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/ebb8/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_gate_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/7161/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/9ac8/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/1f12/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_io_reset_counter_binary_0_1/sim/UFBmod_TRX_TRX_io_reset_counter_binary_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/442e/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_rx09_xlconcat_0_1/sim/UFBmod_TRX_TRX_rx09_xlconcat_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_rx_xlslice_00to00_1/sim/UFBmod_TRX_TRX_rx_xlslice_00to00_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_rx_xlslice_02to02_1/sim/UFBmod_TRX_TRX_rx_xlslice_02to02_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_rx_xlslice_04to04_1/sim/UFBmod_TRX_TRX_rx_xlslice_04to04_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_rx_xlslice_06to06_1/sim/UFBmod_TRX_TRX_rx_xlslice_06to06_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_rx_xlslice_10to10_1/sim/UFBmod_TRX_TRX_rx_xlslice_10to10_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_rx_xlslice_12to12_1/sim/UFBmod_TRX_TRX_rx_xlslice_12to12_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_rx_xlslice_14to14_1/sim/UFBmod_TRX_TRX_rx_xlslice_14to14_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_rx_xlslice_08to08_1/sim/UFBmod_TRX_TRX_rx_xlslice_08to08_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_rx24_xlconcat_0_1/sim/UFBmod_TRX_TRX_rx24_xlconcat_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_rx_xlslice_15to15_1/sim/UFBmod_TRX_TRX_rx_xlslice_15to15_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_rx_xlslice_13to13_1/sim/UFBmod_TRX_TRX_rx_xlslice_13to13_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_rx_xlslice_11to11_1/sim/UFBmod_TRX_TRX_rx_xlslice_11to11_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_rx_xlslice_09to09_1/sim/UFBmod_TRX_TRX_rx_xlslice_09to09_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_rx_xlslice_07to07_1/sim/UFBmod_TRX_TRX_rx_xlslice_07to07_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_rx_xlslice_05to05_1/sim/UFBmod_TRX_TRX_rx_xlslice_05to05_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_rx_xlslice_03to03_1/sim/UFBmod_TRX_TRX_rx_xlslice_03to03_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_rx_xlslice_01to01_1/sim/UFBmod_TRX_TRX_rx_xlslice_01to01_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_rx09_fifo_generator_0_1/sim/UFBmod_TRX_TRX_rx09_fifo_generator_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_rx24_fifo_generator_0_1/sim/UFBmod_TRX_TRX_rx24_fifo_generator_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_tx09_fifo_generator_0_1/sim/UFBmod_TRX_TRX_tx09_fifo_generator_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_tx_LVDS_interleave_xlconcat_0_1/sim/UFBmod_TRX_TRX_tx_LVDS_interleave_xlconcat_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlslice_00to00_1/sim/UFBmod_TRX_xlslice_00to00_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlslice_01to01_1/sim/UFBmod_TRX_xlslice_01to01_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlslice_02to02_1/sim/UFBmod_TRX_xlslice_02to02_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlslice_03to03_1/sim/UFBmod_TRX_xlslice_03to03_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlslice_04to04_1/sim/UFBmod_TRX_xlslice_04to04_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlslice_05to05_1/sim/UFBmod_TRX_xlslice_05to05_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlslice_06to06_1/sim/UFBmod_TRX_xlslice_06to06_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlslice_07to07_1/sim/UFBmod_TRX_xlslice_07to07_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_tx_word_format_xlconcat_0_1/sim/UFBmod_TRX_TRX_tx_word_format_xlconcat_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlconstant_val0_len1_2/sim/UFBmod_TRX_xlconstant_val0_len1_2.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlconstant_val1_len1_5/sim/UFBmod_TRX_xlconstant_val1_len1_5.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_blank_tx_util_vector_logic_0_1/sim/UFBmod_TRX_TRX_blank_tx_util_vector_logic_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_blank_tx_xlconcat_0_1/sim/UFBmod_TRX_TRX_blank_tx_xlconcat_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_blank_tx_util_vector_logic_1_1/sim/UFBmod_TRX_TRX_blank_tx_util_vector_logic_1_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work c_mux_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/ecb4/hdl/c_mux_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_shift_ram_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/2598/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_blank_tx_c_shift_ram_0_1/sim/UFBmod_TRX_TRX_blank_tx_c_shift_ram_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_LVDS_selectio_wiz_0_1/UFBmod_TRX_TRX_LVDS_selectio_wiz_0_1_selectio_wiz.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_LVDS_selectio_wiz_0_1/UFBmod_TRX_TRX_LVDS_selectio_wiz_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlconstant_1_len1_1/sim/UFBmod_TRX_xlconstant_1_len1_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_LVDS_util_ds_buf_0_1/util_ds_buf.vhd" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_LVDS_util_ds_buf_0_1/sim/UFBmod_TRX_TRX_LVDS_util_ds_buf_0_1.vhd" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_c_shift_ram_dly386_1_1/sim/UFBmod_TRX_c_shift_ram_dly386_1_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlconcat_0_2/sim/UFBmod_TRX_xlconcat_0_2.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_fifo_generator_dly2049_0_1/sim/UFBmod_TRX_fifo_generator_dly2049_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlconstant_val1_len1_6/sim/UFBmod_TRX_xlconstant_val1_len1_6.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_16 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/ce84/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work cordic_v6_0_16 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/5bf0/hdl/cordic_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_cordic_rx09_1/sim/UFBmod_TRX_cordic_rx09_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_rx09_xlslice_15to0_1/sim/UFBmod_TRX_rx09_xlslice_15to0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_fft_rx09_s_data_xlconcat_0_1/sim/UFBmod_TRX_fft_rx09_s_data_xlconcat_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_cordic_rx09_xlconcat_0_1/sim/UFBmod_TRX_cordic_rx09_xlconcat_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_cordic_rx09_addra_xlslice_9to0_1/sim/UFBmod_TRX_cordic_rx09_addra_xlslice_9to0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work cmpy_v6_0_18 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/231d/hdl/cmpy_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_0_17 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/096f/hdl/floating_point_v7_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xfft_v9_1_4 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/2a49/hdl/xfft_v9_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xfft_rx09_dly3459_1/sim/UFBmod_TRX_xfft_rx09_dly3459_1.vhd" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_window_rx09_re_mult_gen_0_1/sim/UFBmod_TRX_window_rx09_re_mult_gen_0_1.vhd" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_window_rx09_im_mult_gen_0_1/sim/UFBmod_TRX_window_rx09_im_mult_gen_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_window_coef_rom_blk_mem_gen_0_1/sim/UFBmod_TRX_window_coef_rom_blk_mem_gen_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_pre_fft_rx09_blk_mem_gen_0_1/sim/UFBmod_TRX_pre_fft_rx09_blk_mem_gen_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_post_fft_rx09_blk_mem_gen_0_1/sim/UFBmod_TRX_post_fft_rx09_blk_mem_gen_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_pre_fft_rx09_xlslice_25to13_1/sim/UFBmod_TRX_pre_fft_rx09_xlslice_25to13_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_pre_fft_rx09_xlslice_12to00_1/sim/UFBmod_TRX_pre_fft_rx09_xlslice_12to00_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_post_fft_rx09_xlslice_9downto0_1/sim/UFBmod_TRX_post_fft_rx09_xlslice_9downto0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlconstant_val1_len1_7/sim/UFBmod_TRX_xlconstant_val1_len1_7.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_reduced_logic_v2_0_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/4c94/hdl/util_reduced_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_post_fft_mem_a_rx09_util_reduced_logic_0_1/sim/UFBmod_TRX_post_fft_mem_a_rx09_util_reduced_logic_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_post_fft_mem_a_rx09_xlconcat_0_1/sim/UFBmod_TRX_post_fft_mem_a_rx09_xlconcat_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_pushdata_rx09_xlconcat_0_1/sim/UFBmod_TRX_pushdata_rx09_xlconcat_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_pushdata_rx09_xlslice_31to16_1/sim/UFBmod_TRX_pushdata_rx09_xlslice_31to16_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_pushdata_rx09_xlslice_8to8_1/sim/UFBmod_TRX_pushdata_rx09_xlslice_8to8_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_fifo_generator_0_1/sim/UFBmod_TRX_fifo_generator_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_gpio_xlslice_31downto31_resetn_0_1/sim/UFBmod_TRX_TRX_gpio_xlslice_31downto31_resetn_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_gpio_xlslice_30downto30_rfxmode_0_1/sim/UFBmod_TRX_TRX_gpio_xlslice_30downto30_rfxmode_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_gpio_xlslice_0downto0_blankTx_0_1/sim/UFBmod_TRX_TRX_gpio_xlslice_0downto0_blankTx_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_gpio_xlconcat_0_1/sim/UFBmod_TRX_TRX_gpio_xlconcat_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_PLL_clk_wiz_0_1/UFBmod_TRX_TRX_PLL_clk_wiz_0_1_clk_wiz.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_PLL_clk_wiz_0_1/UFBmod_TRX_TRX_PLL_clk_wiz_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_PLL_util_ds_buf_0_1/sim/UFBmod_TRX_TRX_PLL_util_ds_buf_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_reset_util_vector_logic_0_1/sim/UFBmod_TRX_TRX_reset_util_vector_logic_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_tx_4to1_c_counter_binary_0_1/sim/UFBmod_TRX_TRX_tx_4to1_c_counter_binary_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_tx0_re_xlslice_12to00_1/sim/UFBmod_TRX_TRX_tx0_re_xlslice_12to00_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_tx1_re_xlslice_12to00_1/sim/UFBmod_TRX_TRX_tx1_re_xlslice_12to00_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_tx0_im_xlslice_28to16_1/sim/UFBmod_TRX_TRX_tx0_im_xlslice_28to16_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_tx1_im_xlslice_28to16_1/sim/UFBmod_TRX_TRX_tx1_im_xlslice_28to16_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/b0ac/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_multadd_v3_0_15 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8914/hdl/xbip_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_tx0_re_xbip_multadd_0_1/sim/UFBmod_TRX_TRX_tx0_re_xbip_multadd_0_1.vhd" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_tx0_im_xbip_multadd_0_1/sim/UFBmod_TRX_TRX_tx0_im_xbip_multadd_0_1.vhd" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_CDC_dds_tx0_c_shift_ram_0_1/sim/UFBmod_TRX_TRX_CDC_dds_tx0_c_shift_ram_0_1.vhd" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_CDC_dds_tx1_c_shift_ram_0_1/sim/UFBmod_TRX_TRX_CDC_dds_tx1_c_shift_ram_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_ampt_tx1_xslice_15to8_1/sim/UFBmod_TRX_TRX_ampt_tx1_xslice_15to8_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_ampt_tx1_xslice_7to0_1/sim/UFBmod_TRX_TRX_ampt_tx1_xslice_7to0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_tx1_re_xbip_multadd_0_1/sim/UFBmod_TRX_TRX_tx1_re_xbip_multadd_0_1.vhd" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_tx1_im_xbip_multadd_0_1/sim/UFBmod_TRX_TRX_tx1_im_xbip_multadd_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work dds_compiler_v6_0_20 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/398e/hdl/dds_compiler_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_tx1_dds_compiler_0_1/sim/UFBmod_TRX_TRX_tx1_dds_compiler_0_1.vhd" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_tx0_dds_compiler_0_1/sim/UFBmod_TRX_TRX_tx0_dds_compiler_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlconstant_val0_len1_3/sim/UFBmod_TRX_xlconstant_val0_len1_3.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlconstant_val1_len1_9/sim/UFBmod_TRX_xlconstant_val1_len1_9.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_CDC_ampt_tx0_c_shift_ram_0_1/sim/UFBmod_TRX_TRX_CDC_ampt_tx0_c_shift_ram_0_1.vhd" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_CDC_ampt_tx1_c_shift_ram_0_1/sim/UFBmod_TRX_TRX_CDC_ampt_tx1_c_shift_ram_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_ampt_tx0_xslice_15to8_1/sim/UFBmod_TRX_TRX_ampt_tx0_xslice_15to8_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_ampt_tx0_xslice_7to0_1/sim/UFBmod_TRX_TRX_ampt_tx0_xslice_7to0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_pulldata_tx09_fifo_generator_0_1/sim/UFBmod_TRX_pulldata_tx09_fifo_generator_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlslice_7to0_1/sim/UFBmod_TRX_xlslice_7to0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlslice_30to30_1/sim/UFBmod_TRX_xlslice_30to30_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_pulldata_tx09_c_shift_ram_0_1/sim/UFBmod_TRX_pulldata_tx09_c_shift_ram_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_pulldata_tx09_util_reduced_logic_0_1/sim/UFBmod_TRX_pulldata_tx09_util_reduced_logic_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_pulldata_tx09_util_vector_logic_0_1/sim/UFBmod_TRX_pulldata_tx09_util_vector_logic_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_pulldata_tx09_xlconcat_1_1/sim/UFBmod_TRX_pulldata_tx09_xlconcat_1_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlslice_14to8_1/sim/UFBmod_TRX_xlslice_14to8_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlconcat_0_3/sim/UFBmod_TRX_xlconcat_0_3.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlslice_29to29_1/sim/UFBmod_TRX_xlslice_29to29_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlslice_28to28_1/sim/UFBmod_TRX_xlslice_28to28_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_CDC_dds_tx0_xlconcat_0_1/sim/UFBmod_TRX_TRX_CDC_dds_tx0_xlconcat_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_post_fft_rx09_ad_0_0/sim/UFBmod_TRX_TRX_post_fft_rx09_ad_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_post_fft_rx09_ch00_blk_mem_gen_0_0/sim/UFBmod_TRX_post_fft_rx09_ch00_blk_mem_gen_0_0.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_post_fft_rx09_ch00_blk_mem_gen_0_1/sim/UFBmod_TRX_post_fft_rx09_ch00_blk_mem_gen_0_1.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_post_fft_rx09_ch00_blk_mem_gen_0_2/sim/UFBmod_TRX_post_fft_rx09_ch00_blk_mem_gen_0_2.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_post_fft_rx09_ch00_blk_mem_gen_0_3/sim/UFBmod_TRX_post_fft_rx09_ch00_blk_mem_gen_0_3.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_post_fft_rx09_ch00_blk_mem_gen_0_4/sim/UFBmod_TRX_post_fft_rx09_ch00_blk_mem_gen_0_4.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_post_fft_rx09_ch00_blk_mem_gen_0_5/sim/UFBmod_TRX_post_fft_rx09_ch00_blk_mem_gen_0_5.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_post_fft_rx09_ch00_blk_mem_gen_0_6/sim/UFBmod_TRX_post_fft_rx09_ch00_blk_mem_gen_0_6.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_util_reduced_logic_0_0/sim/UFBmod_TRX_util_reduced_logic_0_0.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlconcat_0_4/sim/UFBmod_TRX_xlconcat_0_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_c_shift_ram_0_0/sim/UFBmod_TRX_c_shift_ram_0_0.vhd" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_FIFO_Arbiter_0_0/sim/UFBmod_TRX_TRX_FIFO_Arbiter_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/UFBmod_TRX/ipshared/8b3d" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_xlconstant_0_0/sim/UFBmod_TRX_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/UFBmod_TRX/ip/UFBmod_TRX_TRX_gpio_xlslice_0to0_blankTx_0_0/sim/UFBmod_TRX_TRX_gpio_xlslice_0to0_blankTx_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/UFBmod_TRX/sim/UFBmod_TRX.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.UFBmod_TRX xil_defaultlib.glbl -o UFBmod_TRX_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./UFBmod_TRX_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./UFBmod_TRX.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key UFBmod_TRX_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc UFBmod_TRX_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./UFBmod_TRX.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: UFBmod_TRX.sh [-help]\n\
Usage: UFBmod_TRX.sh [-lib_map_path]\n\
Usage: UFBmod_TRX.sh [-reset_run]\n\
Usage: UFBmod_TRX.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
