#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.1.1 (64-bit)
#
# Filename    : msys.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Oct 06 22:27:53 +0200 2020
# SW Build 2960000 on Wed Aug  5 22:57:20 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: msys.sh [-help]
# usage: msys.sh [-lib_map_path]
# usage: msys.sh [-noclean_files]
# usage: msys.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'msys.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xpm xil_defaultlib dist_mem_gen_v8_0_13 lib_pkg_v1_0_2 lib_cdc_v1_0_2 lib_srl_fifo_v1_0_2 fifo_generator_v13_2_5 lib_fifo_v1_0_14 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_quad_spi_v3_2_20 axi_timer_v2_0_23 axi_uartlite_v2_0_25 mdm_v3_2_18 microblaze_v11_0_3 axi_intc_v4_1_14 lmb_bram_if_cntlr_v4_0_18 lmb_v10_v3_0_11 blk_mem_gen_v8_4_4 xlconcat_v2_1_3 mii_to_rmii_v2_0_20 proc_sys_reset_v5_0_13 axi_gpio_v2_0_23 xlslice_v1_0_2 axi_iic_v2_0_24 xbip_utils_v3_0_10 c_reg_fd_v12_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_6 xbip_dsp48_addsub_v3_0_6 xbip_addsub_v3_0_6 c_addsub_v12_0_14 c_gate_bit_v12_0_6 xbip_counter_v3_0_6 c_counter_binary_v12_0_14 xlconstant_v1_1_7 axi_utils_v2_0_6 c_mux_bit_v12_0_6 c_shift_ram_v12_0_14 xbip_bram18k_v3_0_6 mult_gen_v12_0_16 cmpy_v6_0_18 floating_point_v7_0_17 xfft_v9_1_4 cordic_v6_0_16 util_vector_logic_v2_0_1 xbip_dsp48_multadd_v3_0_6 dds_compiler_v6_0_20 xbip_multadd_v3_0_15 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_21 axi_data_fifo_v2_1_20 axi_crossbar_v2_1_22 util_reduced_logic_v2_0_4 lib_bmg_v1_0_13 axi_ethernetlite_v3_0_20 axi_clock_converter_v2_1_20 axi_protocol_converter_v2_1_21)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "msys.sh - Script generated by export_simulation (Vivado v2020.1.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "F:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "F:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "F:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "F:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ipshared/97ab/scr/SC0712.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_SC0712_0_0/sim/msys_SC0712_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work dist_mem_gen_v8_0_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/0bf5/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_quad_spi_v3_2_20 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1735/hdl/axi_quad_spi_v3_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_axi_quad_spi_0_0/sim/msys_axi_quad_spi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_timer_v2_0_23 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/eb71/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_axi_timer_0_0/sim/msys_axi_timer_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_25 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/43b7/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_axi_uartlite_0_0/sim/msys_axi_uartlite_0_0.vhd" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/2bc4/labtools_fmeter.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_labtools_fmeter_0_0/sim/msys_labtools_fmeter_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mdm_v3_2_18 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/e9fa/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_mdm_1_0/sim/msys_mdm_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work microblaze_v11_0_3 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1efc/hdl/microblaze_v11_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_microblaze_0_0/sim/msys_microblaze_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_14 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/f78a/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_microblaze_0_axi_intc_0/sim/msys_microblaze_0_axi_intc_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_bram_if_cntlr_v4_0_18 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/246e/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_dlmb_bram_if_cntlr_0/sim/msys_dlmb_bram_if_cntlr_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_v10_v3_0_11 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/c2ed/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_dlmb_v10_0/sim/msys_dlmb_v10_0.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_ilmb_bram_if_cntlr_0/sim/msys_ilmb_bram_if_cntlr_0.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_ilmb_v10_0/sim/msys_ilmb_v10_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_lmb_bram_0/sim/msys_lmb_bram_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/442e/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_microblaze_0_xlconcat_0/sim/msys_microblaze_0_xlconcat_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_addr_decode.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_read.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_reg.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_reg_bank.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_top.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_write.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_ar_channel.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_aw_channel.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_b_channel.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_arbiter.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_fsm.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_translator.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_fifo.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_incr_cmd.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_r_channel.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_simple_fifo.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_wrap_cmd.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_wr_cmd_fsm.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_w_channel.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_axic_register_slice.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_axi_register_slice.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_axi_upsizer.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_a_upsizer.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_and.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_latch_and.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_latch_or.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_or.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_command_fifo.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator_sel.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator_sel_static.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_r_upsizer.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_w_upsizer.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_2_clk_ibuf.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_2_infrastructure.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_2_iodelay_ctrl.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_2_tempmon.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_arb_mux.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_arb_row_col.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_arb_select.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_cntrl.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_common.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_compare.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_mach.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_queue.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_state.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_col_mach.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_mc.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_rank_cntrl.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_rank_common.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_rank_mach.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_round_robin_arb.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_buf.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_dec_fix.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_gen.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_merge_enc.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_2_fi_xor.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v4_2_memc_ui_top_axi.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v4_2_mem_intfc.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_group_io.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_lane.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_calib_top.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_if_post_fifo.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy_wrapper.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_of_pre_fifo.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_4lanes.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ck_addr_cmd_delay.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal_hr.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_init.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_cntlr.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_data.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_edge.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_lim.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_mux.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_po_cntlr.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_samp.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_oclkdelay_cal.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_prbs_rdlvl.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_rdlvl.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_tempmon.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_top.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrcal.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl_off_delay.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_prbs_gen.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_skip_calib_tap.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_cc.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_edge_store.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_meta.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_pd.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_tap_base.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_top.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_2_ui_cmd.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_2_ui_rd_data.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_2_ui_top.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_2_ui_wr_data.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/msys_mig_7series_0_0_mig_sim.v" \
    "$ref_dir/../../../bd/msys/ip/msys_mig_7series_0_0/msys_mig_7series_0_0/user_design/rtl/msys_mig_7series_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work mii_to_rmii_v2_0_20 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/90e9/hdl/mii_to_rmii_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_mii_to_rmii_0_0/sim/msys_mii_to_rmii_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_proc_sys_reset_0_0/sim/msys_proc_sys_reset_0_0.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_proc_sys_reset_eth_0/sim/msys_proc_sys_reset_eth_0.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_rst_mig_7series_0_100M_0/sim/msys_rst_mig_7series_0_100M_0.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_rst_mig_7series_0_50M_0/sim/msys_rst_mig_7series_0_50M_0.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_util_ds_buf_1_0/util_ds_buf.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_util_ds_buf_1_0/sim/msys_util_ds_buf_1_0.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_util_ds_buf_2_0/sim/msys_util_ds_buf_2_0.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_vio_0_0/sim/msys_vio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_0/sim/msys_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_gpio_v2_0_23 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/bb35/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_axi_gpio_0_0/sim/msys_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_1_0/sim/msys_xlconcat_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_0/sim/msys_xlslice_0_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_uart0_xlslice_0_0/sim/msys_uart0_xlslice_0_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_uart0_xlslice_1_0/sim/msys_uart0_xlslice_1_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_uart0_xlslice_1_1/sim/msys_uart0_xlslice_1_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_rst_mig_7series_0_50M_1/sim/msys_rst_mig_7series_0_50M_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_clk_wiz_0_0/msys_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/msys/ip/msys_clk_wiz_0_0/msys_clk_wiz_0_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_1_1/sim/msys_xlconcat_1_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_iic_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/d1e4/hdl/axi_iic_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_axi_iic_1_0/sim/msys_axi_iic_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/d117/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/edec/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/cfdd/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ebb8/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_c_addsub_0_0/sim/msys_c_addsub_0_0.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_RGB_red_c_addsub_0_0/sim/msys_RGB_red_c_addsub_0_0.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_RGB_green_c_addsub_0_0/sim/msys_RGB_green_c_addsub_0_0.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_RGB_blue_compare_0_0/sim/msys_RGB_blue_compare_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_2/sim/msys_xlslice_0_2.v" \
    "$ref_dir/../../../bd/msys/ip/msys_RGB_red_xlslice_0_0/sim/msys_RGB_red_xlslice_0_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_RGB_red_xlslice_0_1/sim/msys_RGB_red_xlslice_0_1.v" \
    "$ref_dir/../../../bd/msys/ip/msys_RGB_red_xlslice_0_2/sim/msys_RGB_red_xlslice_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work c_gate_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/7161/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/9ac8/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1f12/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_c_counter_binary_0_0/sim/msys_c_counter_binary_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_LCD_BL_xlslice_0_0/sim/msys_LCD_BL_xlslice_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_axi_uart0_gpio_0_0/sim/msys_axi_uart0_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_PWM_ctr_xlslice_0_0/sim/msys_PWM_ctr_xlslice_0_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_PWM_gpio_xlslice_3_0/sim/msys_PWM_gpio_xlslice_3_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_PWM_gpio_xlslice_3_1/sim/msys_PWM_gpio_xlslice_3_1.v" \
    "$ref_dir/../../../bd/msys/ip/msys_PWM_gpio_xlslice_3_2/sim/msys_PWM_gpio_xlslice_3_2.v" \
    "$ref_dir/../../../bd/msys/ip/msys_RGB_red_xlslice_0_3/sim/msys_RGB_red_xlslice_0_3.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_1_2/sim/msys_xlconcat_1_2.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconstant_0_0/sim/msys_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_c_counter_binary_0_1/sim/msys_c_counter_binary_0_1.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_axi_pwm_gpio_0_0/sim/msys_axi_pwm_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_axi_pwm_gpio_0_1/sim/msys_axi_pwm_gpio_0_1.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_axi_quad_spi_1_0/sim/msys_axi_quad_spi_1_0.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_axi_ROTENC_gpio_0_0/sim/msys_axi_ROTENC_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_3/sim/msys_xlslice_0_3.v" \
    "$ref_dir/../../../bd/msys/ip/msys_TRX_xlslice_0to0_0_0/sim/msys_TRX_xlslice_0to0_0_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_BOARD_clk_wiz_0_0/msys_BOARD_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/msys/ip/msys_BOARD_clk_wiz_0_0/msys_BOARD_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_util_ds_buf_0_2/sim/msys_util_ds_buf_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_selectio_wiz_0_1/msys_selectio_wiz_0_1_selectio_wiz.v" \
    "$ref_dir/../../../bd/msys/ip/msys_selectio_wiz_0_1/msys_selectio_wiz_0_1.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_4/sim/msys_xlslice_0_4.v" \
    "$ref_dir/../../../bd/msys/ip/msys_TRX_rx_xlslice_15to15_0/sim/msys_TRX_rx_xlslice_15to15_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_TRX_rx_xlslice_15to16_0/sim/msys_TRX_rx_xlslice_15to16_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_TRX_rx_xlslice_13to13_0/sim/msys_TRX_rx_xlslice_13to13_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_TRX_rx_xlslice_13to13_1/sim/msys_TRX_rx_xlslice_13to13_1.v" \
    "$ref_dir/../../../bd/msys/ip/msys_TRX_rx_xlslice_13to13_2/sim/msys_TRX_rx_xlslice_13to13_2.v" \
    "$ref_dir/../../../bd/msys/ip/msys_TRX_rx_xlslice_10to10_0/sim/msys_TRX_rx_xlslice_10to10_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_TRX_rx_xlslice_10to10_1/sim/msys_TRX_rx_xlslice_10to10_1.v" \
    "$ref_dir/../../../bd/msys/ip/msys_TRX_rx_xlslice_10to10_2/sim/msys_TRX_rx_xlslice_10to10_2.v" \
    "$ref_dir/../../../bd/msys/ip/msys_TRX_rx_xlslice_10to10_3/sim/msys_TRX_rx_xlslice_10to10_3.v" \
    "$ref_dir/../../../bd/msys/ip/msys_TRX_rx_xlslice_10to10_4/sim/msys_TRX_rx_xlslice_10to10_4.v" \
    "$ref_dir/../../../bd/msys/ip/msys_TRX_rx_xlslice_10to10_5/sim/msys_TRX_rx_xlslice_10to10_5.v" \
    "$ref_dir/../../../bd/msys/ip/msys_TRX_rx_xlslice_10to10_6/sim/msys_TRX_rx_xlslice_10to10_6.v" \
    "$ref_dir/../../../bd/msys/ip/msys_TRX_rx_xlslice_10to10_7/sim/msys_TRX_rx_xlslice_10to10_7.v" \
    "$ref_dir/../../../bd/msys/ip/msys_TRX_rx_xlslice_10to10_8/sim/msys_TRX_rx_xlslice_10to10_8.v" \
    "$ref_dir/../../../bd/msys/ip/msys_TRX_rx_xlslice_10to10_9/sim/msys_TRX_rx_xlslice_10to10_9.v" \
    "$ref_dir/../../../bd/msys/ip/msys_fifo_generator_0_0/sim/msys_fifo_generator_0_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_TRX_rx09_fifo_generator_0_0/sim/msys_TRX_rx09_fifo_generator_0_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconstant_0b00_1/sim/msys_xlconstant_0b00_1.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_1_3/sim/msys_xlconcat_1_3.v" \
    "$ref_dir/../../../bd/msys/ip/msys_TRX_rx09_xlconcat_0_0/sim/msys_TRX_rx09_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_c_counter_binary_0_2/sim/msys_c_counter_binary_0_2.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_proc_sys_reset_0_1/sim/msys_proc_sys_reset_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_mux_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ecb4/hdl/c_mux_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_shift_ram_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/2598/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_16 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ce84/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work cmpy_v6_0_18 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/231d/hdl/cmpy_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_0_17 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/096f/hdl/floating_point_v7_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xfft_v9_1_4 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/2a49/hdl/xfft_v9_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_xfft_0_0/sim/msys_xfft_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_blk_mem_gen_0_0/sim/msys_blk_mem_gen_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_dly1024_1_0/sim/msys_c_shift_ram_dly1024_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work cordic_v6_0_16 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/5bf0/hdl/cordic_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_cordic_0_0/sim/msys_cordic_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_blk_mem_gen_0_2/sim/msys_blk_mem_gen_0_2.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_util_vector_logic_0_4/sim/msys_util_vector_logic_0_4.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_19/sim/msys_xlslice_0_19.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_1/sim/msys_xlconcat_0_1.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_21/sim/msys_xlslice_0_21.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_1_0/sim/msys_xlslice_1_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_24/sim/msys_xlslice_0_24.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_4/sim/msys_xlconcat_0_4.v" \
    "$ref_dir/../../../bd/msys/ip/msys_TRX_rx09_fifo_generator_0_1/sim/msys_TRX_rx09_fifo_generator_0_1.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_6/sim/msys_xlconcat_0_6.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconstant_0_14/sim/msys_xlconstant_0_14.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_26/sim/msys_xlslice_0_26.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_1_1/sim/msys_xlslice_1_1.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_2_0/sim/msys_xlslice_2_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_3_0/sim/msys_xlslice_3_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_4_0/sim/msys_xlslice_4_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_5_0/sim/msys_xlslice_5_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_6_0/sim/msys_xlslice_6_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_7_0/sim/msys_xlslice_7_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/b0ac/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work dds_compiler_v6_0_20 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/398e/hdl/dds_compiler_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_dds_compiler_0_0/sim/msys_dds_compiler_0_0.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_TRX_tx_dds_compiler_0_0/sim/msys_TRX_tx_dds_compiler_0_0.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_counter_binary_0_3/sim/msys_c_counter_binary_0_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_27/sim/msys_xlslice_0_27.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_1_2/sim/msys_xlslice_1_2.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_28/sim/msys_xlslice_0_28.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_1_3/sim/msys_xlslice_1_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_multadd_v3_0_15 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8914/hdl/xbip_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_xbip_multadd_0_0/sim/msys_xbip_multadd_0_0.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_xbip_multadd_0_1/sim/msys_xbip_multadd_0_1.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_axi_gpio_0_1/sim/msys_axi_gpio_0_1.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_3/sim/msys_c_shift_ram_0_3.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_4/sim/msys_c_shift_ram_0_4.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_30/sim/msys_xlslice_0_30.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_32/sim/msys_xlslice_0_32.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_xbip_multadd_0_2/sim/msys_xbip_multadd_0_2.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_xbip_multadd_0_3/sim/msys_xbip_multadd_0_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_7/sim/msys_xlconcat_0_7.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconstant_0_15/sim/msys_xlconstant_0_15.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconstant_0_16/sim/msys_xlconstant_0_16.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconstant_0_17/sim/msys_xlconstant_0_17.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/2ef9/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/47c9/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/b68e/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xbar_2/sim/msys_xbar_2.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xbar_3/sim/msys_xbar_3.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_33/sim/msys_xlslice_0_33.v" \
    "$ref_dir/../../../bd/msys/ip/msys_util_vector_logic_0_5/sim/msys_util_vector_logic_0_5.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_CLK0_util_ds_buf_0_0/sim/msys_CLK0_util_ds_buf_0_0.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_5/sim/msys_c_shift_ram_0_5.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_34/sim/msys_xlslice_0_34.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_35/sim/msys_xlslice_0_35.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_10/sim/msys_xlconcat_0_10.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconstant_0_19/sim/msys_xlconstant_0_19.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_36/sim/msys_xlslice_0_36.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconstant_0_20/sim/msys_xlconstant_0_20.v" \
    "$ref_dir/../../../bd/msys/ip/msys_clk_wiz_0_1/msys_clk_wiz_0_1_mmcm_pll_drp.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_clk_wiz_0_1/proc_common_v3_00_a/hdl/src/vhdl/msys_clk_wiz_0_1_conv_funs_pkg.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_clk_wiz_0_1/proc_common_v3_00_a/hdl/src/vhdl/msys_clk_wiz_0_1_proc_common_pkg.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_clk_wiz_0_1/proc_common_v3_00_a/hdl/src/vhdl/msys_clk_wiz_0_1_ipif_pkg.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_clk_wiz_0_1/proc_common_v3_00_a/hdl/src/vhdl/msys_clk_wiz_0_1_family_support.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_clk_wiz_0_1/proc_common_v3_00_a/hdl/src/vhdl/msys_clk_wiz_0_1_family.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_clk_wiz_0_1/proc_common_v3_00_a/hdl/src/vhdl/msys_clk_wiz_0_1_soft_reset.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_clk_wiz_0_1/proc_common_v3_00_a/hdl/src/vhdl/msys_clk_wiz_0_1_pselect_f.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_clk_wiz_0_1/axi_lite_ipif_v1_01_a/hdl/src/vhdl/msys_clk_wiz_0_1_address_decoder.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_clk_wiz_0_1/axi_lite_ipif_v1_01_a/hdl/src/vhdl/msys_clk_wiz_0_1_slave_attachment.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_clk_wiz_0_1/axi_lite_ipif_v1_01_a/hdl/src/vhdl/msys_clk_wiz_0_1_axi_lite_ipif.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_clk_wiz_0_1/msys_clk_wiz_0_1_clk_wiz_drp.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_clk_wiz_0_1/msys_clk_wiz_0_1_axi_clk_config.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_clk_wiz_0_1/msys_clk_wiz_0_1_clk_wiz.v" \
    "$ref_dir/../../../bd/msys/ip/msys_clk_wiz_0_1/msys_clk_wiz_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_6/sim/msys_c_shift_ram_0_6.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_7/sim/msys_c_shift_ram_0_7.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_11/sim/msys_xlconcat_0_11.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_8/sim/msys_c_shift_ram_0_8.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_axi_gpio_0_2/sim/msys_axi_gpio_0_2.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_9/sim/msys_c_shift_ram_0_9.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_37/sim/msys_xlslice_0_37.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_1_4/sim/msys_xlslice_1_4.v" \
    "$ref_dir/../../../bd/msys/ip/msys_util_vector_logic_0_7/sim/msys_util_vector_logic_0_7.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_reduced_logic_v2_0_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/4c94/hdl/util_reduced_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_util_reduced_logic_0_0/sim/msys_util_reduced_logic_0_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_12/sim/msys_xlconcat_0_12.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_axi_gpio_0_3/sim/msys_axi_gpio_0_3.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_counter_binary_0_4/sim/msys_c_counter_binary_0_4.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_13/sim/msys_xlconcat_0_13.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_10/sim/msys_c_shift_ram_0_10.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_fifo_generator_0_1/sim/msys_fifo_generator_0_1.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_16/sim/msys_xlconcat_0_16.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_axi_gpio_0_4/sim/msys_axi_gpio_0_4.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_39/sim/msys_xlslice_0_39.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_1_5/sim/msys_xlslice_1_5.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_11/sim/msys_c_shift_ram_0_11.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_12/sim/msys_c_shift_ram_0_12.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_13/sim/msys_c_shift_ram_0_13.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_14/sim/msys_c_shift_ram_0_14.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_15/sim/msys_c_shift_ram_0_15.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_16/sim/msys_c_shift_ram_0_16.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_17/sim/msys_c_shift_ram_0_17.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_18/sim/msys_c_shift_ram_0_18.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_19/sim/msys_c_shift_ram_0_19.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_20/sim/msys_c_shift_ram_0_20.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_21/sim/msys_c_shift_ram_0_21.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_22/sim/msys_c_shift_ram_0_22.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_17/sim/msys_xlconcat_0_17.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_13 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/af67/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_ethernetlite_v3_0_20 $vhdlan_opts \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/e293/hdl/axi_ethernetlite_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_axi_ethernetlite_0_1/sim/msys_axi_ethernetlite_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconstant_0_26/sim/msys_xlconstant_0_26.v" \
    "$ref_dir/../../../bd/msys/ip/msys_util_reduced_logic_0_1/sim/msys_util_reduced_logic_0_1.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_18/sim/msys_xlconcat_0_18.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_c_counter_binary_0_5/sim/msys_c_counter_binary_0_5.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_util_vector_logic_0_8/sim/msys_util_vector_logic_0_8.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_microblaze_0_1/sim/msys_microblaze_0_1.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_lmb_bram_if_cntlr_0_0/sim/msys_lmb_bram_if_cntlr_0_0.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_lmb_v10_0_0/sim/msys_lmb_v10_0_0.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_lmb_v10_1_0/sim/msys_lmb_v10_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_blk_mem_gen_0_3/sim/msys_blk_mem_gen_0_3.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xbar_4/sim/msys_xbar_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_axi_gpio_0_5/sim/msys_axi_gpio_0_5.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_axi_iic_0_1/sim/msys_axi_iic_0_1.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_lmb_bram_if_cntlr_0_1/sim/msys_lmb_bram_if_cntlr_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_clk_wiz_0_2/msys_clk_wiz_0_2_clk_wiz.v" \
    "$ref_dir/../../../bd/msys/ip/msys_clk_wiz_0_2/msys_clk_wiz_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_c_counter_binary_0_6/sim/msys_c_counter_binary_0_6.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_23/sim/msys_c_shift_ram_0_23.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_axi_gpio_0_6/sim/msys_axi_gpio_0_6.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_24/sim/msys_c_shift_ram_0_24.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_40/sim/msys_xlslice_0_40.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_1_6/sim/msys_xlslice_1_6.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_42/sim/msys_xlslice_0_42.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_19/sim/msys_xlconcat_0_19.v" \
    "$ref_dir/../../../bd/msys/ip/msys_util_vector_logic_0_9/sim/msys_util_vector_logic_0_9.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_1_4/sim/msys_xlconcat_1_4.v" \
    "$ref_dir/../../../bd/msys/ip/msys_util_vector_logic_0_10/sim/msys_util_vector_logic_0_10.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_25/sim/msys_c_shift_ram_0_25.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_util_ds_buf_0_3/sim/msys_util_ds_buf_0_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_43/sim/msys_xlslice_0_43.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_44/sim/msys_xlslice_0_44.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_20/sim/msys_xlconcat_0_20.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_21/sim/msys_xlconcat_0_21.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_axi_gpio_0_7/sim/msys_axi_gpio_0_7.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_26/sim/msys_c_shift_ram_0_26.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_27/sim/msys_c_shift_ram_0_27.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_45/sim/msys_xlslice_0_45.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_46/sim/msys_xlslice_0_46.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_47/sim/msys_xlslice_0_47.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_48/sim/msys_xlslice_0_48.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_22/sim/msys_xlconcat_0_22.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_mult_gen_0_0/sim/msys_mult_gen_0_0.vhd" \
    "$ref_dir/../../../bd/msys/ip/msys_window_rx09_re_mult_gen_0_0/sim/msys_window_rx09_re_mult_gen_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_blk_mem_gen_0_5/sim/msys_blk_mem_gen_0_5.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_53/sim/msys_xlslice_0_53.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconstant_0_27/sim/msys_xlconstant_0_27.v" \
    "$ref_dir/../../../bd/msys/ip/msys_util_reduced_logic_0_2/sim/msys_util_reduced_logic_0_2.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_24/sim/msys_xlconcat_0_24.v" \
    "$ref_dir/../../../bd/msys/ip/msys_fifo_generator_0_2/sim/msys_fifo_generator_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_axi_gpio_0_8/sim/msys_axi_gpio_0_8.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_25/sim/msys_xlconcat_0_25.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_56/sim/msys_xlslice_0_56.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_c_shift_ram_0_28/sim/msys_c_shift_ram_0_28.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_util_vector_logic_0_11/sim/msys_util_vector_logic_0_11.v" \
    "$ref_dir/../../../bd/msys/ip/msys_util_reduced_logic_0_3/sim/msys_util_reduced_logic_0_3.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_27/sim/msys_xlconcat_0_27.v" \
    "$ref_dir/../../../bd/msys/ip/msys_fifo_generator_0_3/sim/msys_fifo_generator_0_3.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconstant_0_28/sim/msys_xlconstant_0_28.v" \
    "$ref_dir/../../../bd/msys/ip/msys_pushdata_rx09_fifo_generator_0_0/sim/msys_pushdata_rx09_fifo_generator_0_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_57/sim/msys_xlslice_0_57.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_58/sim/msys_xlslice_0_58.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/ip/msys_pushdata_rx09_c_shift_ram_0_0/sim/msys_pushdata_rx09_c_shift_ram_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_pushdata_rx09_util_reduced_logic_0_0/sim/msys_pushdata_rx09_util_reduced_logic_0_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_pushdata_rx09_util_vector_logic_0_0/sim/msys_pushdata_rx09_util_vector_logic_0_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_pushdata_rx09_xlconcat_1_0/sim/msys_pushdata_rx09_xlconcat_1_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_59/sim/msys_xlslice_0_59.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_28/sim/msys_xlconcat_0_28.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_60/sim/msys_xlslice_0_60.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_61/sim/msys_xlslice_0_61.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlslice_0_62/sim/msys_xlslice_0_62.v" \
    "$ref_dir/../../../bd/msys/ip/msys_xlconcat_0_29/sim/msys_xlconcat_0_29.v" \
    "$ref_dir/../../../bd/msys/ip/msys_tier2_xbar_0_0/sim/msys_tier2_xbar_0_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_tier2_xbar_1_0/sim/msys_tier2_xbar_1_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_tier2_xbar_2_0/sim/msys_tier2_xbar_2_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/7589/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_auto_cc_0/sim/msys_auto_cc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8dfa/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/8b3d" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../TE0712-02-100-2C3_V2.srcs/sources_1/bd/msys/ipshared/46fd/hdl" \
    "$ref_dir/../../../bd/msys/ip/msys_auto_pc_0/sim/msys_auto_pc_0.v" \
    "$ref_dir/../../../bd/msys/ip/msys_auto_cc_1/sim/msys_auto_cc_1.v" \
    "$ref_dir/../../../bd/msys/ip/msys_auto_pc_1/sim/msys_auto_pc_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/msys/sim/msys.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.msys xil_defaultlib.glbl -o msys_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./msys_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./msys.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key msys_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc msys_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./msys.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: msys.sh [-help]\n\
Usage: msys.sh [-lib_map_path]\n\
Usage: msys.sh [-reset_run]\n\
Usage: msys.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
