@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon May 25 11:19:15 +0200 2020
REM SW Build 2729669 on Thu Dec  5 04:49:17 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_null_behav -key {Behavioral:sim_1:Functional:tb_null} -tclbatch tb_null.tcl -protoinst "protoinst_files/bd_cf59.protoinst" -protoinst "protoinst_files/msys.protoinst" -view C:/Users/espero/git/UFBmod/FPGA/TE0712-02-100-2C3_V2/vivado/tb_null_behav.wcfg -view C:/Users/espero/git/UFBmod/FPGA/TE0712-02-100-2C3_V2/vivado/tb_null_behav_RX.wcfg -view C:/Users/espero/git/UFBmod/FPGA/TE0712-02-100-2C3_V2/vivado/tb_null_behav_TX.wcfg -log simulate.log"
call xsim  tb_null_behav -key {Behavioral:sim_1:Functional:tb_null} -tclbatch tb_null.tcl -protoinst "protoinst_files/bd_cf59.protoinst" -protoinst "protoinst_files/msys.protoinst" -view C:/Users/espero/git/UFBmod/FPGA/TE0712-02-100-2C3_V2/vivado/tb_null_behav.wcfg -view C:/Users/espero/git/UFBmod/FPGA/TE0712-02-100-2C3_V2/vivado/tb_null_behav_RX.wcfg -view C:/Users/espero/git/UFBmod/FPGA/TE0712-02-100-2C3_V2/vivado/tb_null_behav_TX.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
