@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Jul 30 20:20:09 +0200 2020
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_SCOPE_behav -key {Behavioral:sim_1:Functional:tb_SCOPE} -tclbatch tb_SCOPE.tcl -protoinst "protoinst_files/bd_cf59.protoinst" -protoinst "protoinst_files/msys.protoinst" -view C:/Users/espero/git/UFBmod/FPGA/TE0712-02-100-2C3_V2/vivado/tb_null_behav.wcfg -view C:/Users/espero/git/UFBmod/FPGA/TE0712-02-100-2C3_V2/vivado/tb_null_behav_RX.wcfg -view C:/Users/espero/git/UFBmod/FPGA/TE0712-02-100-2C3_V2/vivado/tb_null_behav_TX.wcfg -log simulate.log"
call xsim  tb_SCOPE_behav -key {Behavioral:sim_1:Functional:tb_SCOPE} -tclbatch tb_SCOPE.tcl -protoinst "protoinst_files/bd_cf59.protoinst" -protoinst "protoinst_files/msys.protoinst" -view C:/Users/espero/git/UFBmod/FPGA/TE0712-02-100-2C3_V2/vivado/tb_null_behav.wcfg -view C:/Users/espero/git/UFBmod/FPGA/TE0712-02-100-2C3_V2/vivado/tb_null_behav_RX.wcfg -view C:/Users/espero/git/UFBmod/FPGA/TE0712-02-100-2C3_V2/vivado/tb_null_behav_TX.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
