
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.1.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_CFG_SI5338_CFG_SI5338_AXI_GPIO_0_DEVICE_ID,
		XPAR_CFG_SI5338_CFG_SI5338_AXI_GPIO_0_BASEADDR,
		XPAR_CFG_SI5338_CFG_SI5338_AXI_GPIO_0_INTERRUPT_PRESENT,
		XPAR_CFG_SI5338_CFG_SI5338_AXI_GPIO_0_IS_DUAL
	},
	{
		XPAR_CFG_SI5338_CFG_SI5338_DBG_AXI_GPIO_0_DEVICE_ID,
		XPAR_CFG_SI5338_CFG_SI5338_DBG_AXI_GPIO_0_BASEADDR,
		XPAR_CFG_SI5338_CFG_SI5338_DBG_AXI_GPIO_0_INTERRUPT_PRESENT,
		XPAR_CFG_SI5338_CFG_SI5338_DBG_AXI_GPIO_0_IS_DUAL
	}
};


