
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.1.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xemaclite.h"

/*
* The configuration table for devices
*/

XEmacLite_Config XEmacLite_ConfigTable[XPAR_XEMACLITE_NUM_INSTANCES] =
{
	{
		XPAR_ETH0_ETH0_AXI_ETHERNETLITE_0_DEVICE_ID,
		XPAR_ETH0_ETH0_AXI_ETHERNETLITE_0_BASEADDR,
		XPAR_ETH0_ETH0_AXI_ETHERNETLITE_0_TX_PING_PONG,
		XPAR_ETH0_ETH0_AXI_ETHERNETLITE_0_RX_PING_PONG,
		XPAR_ETH0_ETH0_AXI_ETHERNETLITE_0_INCLUDE_MDIO,
		XPAR_ETH0_ETH0_AXI_ETHERNETLITE_0_INCLUDE_INTERNAL_LOOPBACK
	}
};


