webtalk_init -webtalk_dir C:\\Users\\habel\\git\\UFBmod\\SW\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-03-27 11:11:45" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "v88dn3d6ftpree69noghk7m90" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3292 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.057 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1553670955145" -context "sdk\\\\bsp/1553670955145"
webtalk_add_data -client sdk -key hwid -value "1553602780901" -context "sdk\\\\bsp/1553670955145"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1553670955145"
webtalk_add_data -client sdk -key apptemplate -value "srec_spi_bootloader" -context "sdk\\\\bsp/1553670955145"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1553670955145"
webtalk_add_data -client sdk -key uid -value "1553670957783" -context "sdk\\\\application/1553670957783"
webtalk_add_data -client sdk -key hwid -value "1553602780901" -context "sdk\\\\application/1553670957783"
webtalk_add_data -client sdk -key bspid -value "1553670955145" -context "sdk\\\\application/1553670957783"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1553670957783"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1553670957783"
webtalk_add_data -client sdk -key apptemplate -value "srec_spi_bootloader" -context "sdk\\\\application/1553670957783"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1553670957783"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1553670957783"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1553670957783"
webtalk_add_data -client sdk -key projSize -value "132.3828125" -context "sdk\\\\application/1553670957783"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1553681505378"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1553681505378"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1553681505378"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1553681505378"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1553681505378"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1553681505378"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1553681505378"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1553681505378"
webtalk_transmit -clientid 2297065078 -regid "" -xml C:\\Users\\habel\\git\\UFBmod\\SW\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\habel\\git\\UFBmod\\SW\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\habel\\git\\UFBmod\\SW\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
